version: '3.8'

services:
  inventory-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: SecretPassword123
      POSTGRES_DB: inventory_db

  inventory-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production # 🟢 Switch to Production mode on the cloud
      - DATABASE_CONNECTION=${DATABASE_CONNECTION}
      - JWT_Key=${JWT_Key}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - HASHIDS_SALT=${HASHIDS_SALT}